005-Python-Web-Basics/books/urls.py
from django.urls import path

from books.views import index, create, edit

urlpatterns = [
    path('', index, name='index'),
    path('create/', create, name='create book'),
    path('edit/<int:pk>', edit, name='edit book'),
]

005-Python-Web-Basics/django_101/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django_102.urls')),
    path('todo/', include('todos_app.urls')),
    path('books/', include('books.urls')),
    path('testing/', include('testing.urls')),
]

005-Python-Web-Basics/books/models.py
from django.db import models


# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=30)
    pages = models.IntegerField(default=0)
    description = models.TextField(max_length=100, default='')
    author = models.CharField(max_length=20)

005-Python-Web-Basics/books/forms.py
from django import forms
from django.core.exceptions import ValidationError

from books.models import Book


class BookForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.add_form_control_class()

    def add_form_control_class(self):
        for (_, field) in self.fields.items():
            field.widget.attrs['class'] = ' form-control'

    def clean_pages(self):
        pages = self.cleaned_data['pages']
        if pages <= 0:
            raise ValidationError('Pages should be more than 1')
        return pages

    class Meta:
        model = Book
        fields = '__all__'

005-Python-Web-Basics/books/views.py
from django.shortcuts import render, redirect

# Create your views here.
from books.forms import BookForm
from books.models import Book


def index(request):
    context = {
        'books': Book.objects.all(),
    }
    return render(request, 'books/index.html', context)


def create(request):
    return persist(request, Book(), 'create')


def edit(request, pk):
    return persist(request, Book.objects.get(pk=pk), 'edit')


def persist(request, book, template_name):
    if request.method == 'GET':
        context = {
            'form': BookForm(instance=book),
        }
        return render(request, f'books/{template_name}.html', context)
    else:
        form = BookForm(request.POST, instance=book)
        if form.is_valid():
            form.save()
            return redirect('index')
        else:
            context = {
                'form': form,
            }
            return render(request, f'books/{template_name}.html', context)

005-Python-Web-Basics/templates/books/create.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Model Forms Demo</title>
</head>
<body>
    <h1 class="display-4 text-center">Please fill out the form!</h1>
    <form method="post" class="m-auto w-25">
        {% csrf_token %}
        {{ form.errors }}
        <div class="form-group">
            <label for="id_title">Title</label>
            {{ form.title }}
        </div>
        <div class="form-group">
            <label for="id_description">Description</label>
            {{ form.description }}
        </div>
        <div class="form-group">
            <label for="id_pages">Pages</label>
            {{ form.pages }}
        </div>
        <div class="form-group">
            <label for="id_author">Author</label>
            {{ form.author }}
        </div>
        <button type="submit" class="btn btn-primary mx-auto">Submit</button>
    </form>
</body>
</html>

005-Python-Web-Basics/templates/books/edit.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Model Forms Demo</title>
</head>
<body>
    <h1 class="display-4 text-center">Edit the book</h1>
    <form method="post" class="m-auto w-25">
        {% csrf_token %}
        {{ form.errors }}
        <div class="form-group">
            <label for="id_title">Title</label>
            {{ form.title }}
        </div>
        <div class="form-group">
            <label for="id_description">Description</label>
            {{ form.description }}
        </div>
        <div class="form-group">
            <label for="id_pages">Pages</label>
            {{ form.pages }}
        </div>
        <div class="form-group">
            <label for="id_author">Author</label>
            {{ form.author }}
        </div>
        <button type="submit" class="btn btn-primary mx-auto">Edit</button>
    </form>
</body>
</html>

005-Python-Web-Basics/templates/books/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Model Forms Demo</title>
</head>
<body>
    <a class="text-light btn btn-success mt-2 ml-2" href="{% url 'create book' %}">Create new Book</a>
    <p class="display-4 mt-2 ml-2">All books</p>
    <div class="d-flex justify-content-start">
        {% for book in books %}
        <div class="card m-2" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ book.title }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ book.author }}</h6>
                <p class="card-text">{{ book.description }}</p>
                <h6 class="card-subtitle mb-2 text-muted">{{ book.pages }} pages</h6>
                <a class="text-light btn btn-primary" href="{% url 'edit book' book.pk %}">Edit</a>
            </div>
        </div>
        {% endfor %}
    </div>
</body>
</html>